---
language: "de"
default_pipeline: "mate"
modelDir: "${user.home}/data/pynlp/data"
pipelines:
  de.mate: 
  - !<de.versley.exml.annotators.MATEAnnotator>
    lemma_fname: "mate_models/lemma-ger-3.6.model"
    parser_fname: "mate_models/pet-ger-S2a-40-0.25-0.1-2-2-ht4-hm4-kk0"
  en.mate:
  - !<de.versley.exml.annotators.MATEAnnotator>
    lemma_fname: null
    parser_fname: "mate_models/per-eng-S2b-40.mdl"
  fr.mate:
  - !<de.versley.exml.annotators.MATEAnnotator>
    lemma_fname: "mate_models/lemma-fra.mdl"
    parser_fname: "mate_models/pet-fra-S2apply-40-0.25-0.1-2-2-ht4-hm4-kk0"
  de.pcfgla:
  - !<de.versley.exml.annotators.BPAnnotator>
    modelName: "berkeley/r6_train2.gr"
    transforms:
    - !<de.versley.exml.treetransform.NodeToFunction> {}
  fr.pcfgla:
  - !<de.versley.exml.annotators.BPAnnotator>
    modelName: "berkeley/train.French.gold.ptb.train.gr"
    transforms:
    - !<de.versley.exml.treetransform.NodeToFunction> {}
  fr.bonsai:
  - !<de.versley.exml.annotators.BPAnnotator>
    modelName: "${user.home}/sources/bonsai_v3.2/resources/bkygram/gram-ftbuc+dfl+clust0-200-v6"
    preprocess: !<de.versley.exml.annotators.preprocess.BonsaiPreprocessor>
      bonsaiDir: "${user.home}/sources/bonsai_v3.2"
  en.corenlp:
  - !<de.versley.exml.annotators.CoreNLPAnnotator>
    annotators: [pos, lemma, ner, parse, dcoref]
  de.corenlp:
  - !<de.versley.exml.annotators.MATEAnnotator>
    lemma_fname: "mate_models/lemma-ger-3.6.model"
    parser_fname: "mate_models/pet-ger-S2a-40-0.25-0.1-2-2-ht4-hm4-kk0"
  - !<de.versley.exml.annotators.CoreNLPAnnotator>
    annotators: [ner]
    nerModel: stanford/hgc_175m_600.crf.ser.gz
    properties:
      ner.applyNumericClassifiers: false
      ner.useSUTime: false
